/**
 * @packageDocumentation
 * @module api.functional.leagues.settings
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  CreateLeagueSettingsDto,
  ILeagueSettings,
} from "@/leagues/entities/league-settings.entity";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

export * as latest from "./latest/index";

/**
 * Create a new set of league settings for a league (versioned by time).
 * Path param takes precedence over any leagueId present in the body.
 * @controller LeaguesController.createLeagueSettings
 * @path POST /leagues/:id/settings
 * @accessor api.functional.leagues.settings.createLeagueSettings
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createLeagueSettings(
  connection: IConnection,
  leagueId: string,
  body: createLeagueSettings.Body,
): Promise<createLeagueSettings.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createLeagueSettings.METADATA,
      template: createLeagueSettings.METADATA.path,
      path: createLeagueSettings.path(leagueId),
    },
    body,
  );
}
export namespace createLeagueSettings {
  export type Body = Primitive<CreateLeagueSettingsDto>;
  export type Output = Primitive<ILeagueSettings>;

  export const METADATA = {
    method: "POST",
    path: "/leagues/:id/settings",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (leagueId: string) =>
    `/leagues/${encodeURIComponent(leagueId?.toString() ?? "null")}/settings`;
}

/**
 * Fetch a specific league settings by its id.
 * @controller LeaguesController.getLeagueSettingsById
 * @path GET /leagues/settings/:settingsId
 * @accessor api.functional.leagues.settings.getLeagueSettingsById
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLeagueSettingsById(
  connection: IConnection,
  settingsId: string,
): Promise<getLeagueSettingsById.Output> {
  return PlainFetcher.fetch(connection, {
    ...getLeagueSettingsById.METADATA,
    template: getLeagueSettingsById.METADATA.path,
    path: getLeagueSettingsById.path(settingsId),
  });
}
export namespace getLeagueSettingsById {
  export type Output = Primitive<ILeagueSettings>;

  export const METADATA = {
    method: "GET",
    path: "/leagues/settings/:settingsId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (settingsId: string) =>
    `/leagues/settings/${encodeURIComponent(settingsId?.toString() ?? "null")}`;
}
