/**
 * @packageDocumentation
 * @module api.functional.sleeper.projections
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { SleeperStatRequest } from "@/sleeper/entities/sleeper.entity";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive, Resolved } from "typia";

import type { SleeperProjectionResponse } from "../../../../../../sleeper/entities/sleeper.entity";

/**
 * @controller SleeperController.getProjections
 * @path GET /sleeper/projections/:year/:week
 * @accessor api.functional.sleeper.projections.getProjections
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getProjections(
  connection: IConnection,
  year: number,
  week: number,
  query: getProjections.Query,
): Promise<getProjections.Output> {
  return PlainFetcher.fetch(connection, {
    ...getProjections.METADATA,
    template: getProjections.METADATA.path,
    path: getProjections.path(year, week, query),
  });
}
export namespace getProjections {
  export type Query = Resolved<SleeperStatRequest>;
  export type Output = Primitive<SleeperProjectionResponse>;

  export const METADATA = {
    method: "GET",
    path: "/sleeper/projections/:year/:week",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (year: number, week: number, query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/sleeper/projections/${encodeURIComponent(year?.toString() ?? "null")}/${encodeURIComponent(week?.toString() ?? "null")}`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
