/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface League {
  leagueId: Generated<number | null>;
  name: string;
}

export interface LeagueUser {
  leagueId: number;
  role: string;
  userId: number;
}

export interface Team {
  leagueId: number;
  playerId: number;
  playerName: string;
  position: string;
  seasonYear: number;
  teamId: Generated<number | null>;
  userId: number;
  week: number;
}

export interface User {
  email: string;
  name: string;
  userId: Generated<number | null>;
}

export interface DB {
  league: League;
  leagueUser: LeagueUser;
  team: Team;
  user: User;
}
