/**
 * @packageDocumentation
 * @module api.functional.leagues
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  CreateLeagueDto,
  League,
  UpdateLeagueDto,
} from "@/leagues/entities/league.entity";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

export * as users from "./users/index";
export * as teams from "./teams/index";

/**
 * @controller LeaguesController.create
 * @path POST /leagues
 * @accessor api.functional.leagues.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createLeagueDto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    createLeagueDto,
  );
}
export namespace create {
  export type Body = Primitive<CreateLeagueDto>;
  export type Output = Primitive<League>;

  export const METADATA = {
    method: "POST",
    path: "/leagues",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/leagues";
}

/**
 * @controller LeaguesController.findAll
 * @path GET /leagues
 * @accessor api.functional.leagues.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(),
  });
}
export namespace findAll {
  export type Output = Primitive<League[]>;

  export const METADATA = {
    method: "GET",
    path: "/leagues",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/leagues";
}

/**
 * @controller LeaguesController.findOne
 * @path GET /leagues/:id
 * @accessor api.functional.leagues.findOne
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    template: findOne.METADATA.path,
    path: findOne.path(id),
  });
}
export namespace findOne {
  export type Output = Primitive<League>;

  export const METADATA = {
    method: "GET",
    path: "/leagues/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/leagues/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller LeaguesController.update
 * @path PATCH /leagues/:id
 * @accessor api.functional.leagues.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  updateLeagueDto: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    updateLeagueDto,
  );
}
export namespace update {
  export type Body = Primitive<UpdateLeagueDto>;
  export type Output = Primitive<League>;

  export const METADATA = {
    method: "PATCH",
    path: "/leagues/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/leagues/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller LeaguesController.remove
 * @path DELETE /leagues/:id
 * @accessor api.functional.leagues.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    template: remove.METADATA.path,
    path: remove.path(id),
  });
}
export namespace remove {
  export const METADATA = {
    method: "DELETE",
    path: "/leagues/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/leagues/${encodeURIComponent(id?.toString() ?? "null")}`;
}
