/**
 * @packageDocumentation
 * @module api.functional.leagues.settings.latest
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { ILeagueSettings } from "@/leagues/entities/league-settings.entity";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * Fetch the latest (most recently created) league settings for a league.
 * @controller LeaguesController.getLatestLeagueSettings
 * @path GET /leagues/:id/settings/latest
 * @accessor api.functional.leagues.settings.latest.getLatestLeagueSettings
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLatestLeagueSettings(
  connection: IConnection,
  leagueId: string,
): Promise<getLatestLeagueSettings.Output> {
  return PlainFetcher.fetch(connection, {
    ...getLatestLeagueSettings.METADATA,
    template: getLatestLeagueSettings.METADATA.path,
    path: getLatestLeagueSettings.path(leagueId),
  });
}
export namespace getLatestLeagueSettings {
  export type Output = Primitive<ILeagueSettings>;

  export const METADATA = {
    method: "GET",
    path: "/leagues/:id/settings/latest",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (leagueId: string) =>
    `/leagues/${encodeURIComponent(leagueId?.toString() ?? "null")}/settings/latest`;
}
