/**
 * @packageDocumentation
 * @module api.functional.teams.players
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type {
  CreateTeamPlayerDto,
  TeamPlayer,
} from "@/teams/entities/team-player.entity";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * @controller TeamsController.upsertTeamPlayer
 * @path PUT /teams/:teamId/players
 * @accessor api.functional.teams.players.upsertTeamPlayer
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function upsertTeamPlayer(
  connection: IConnection,
  teamId: string,
  dto: upsertTeamPlayer.Body,
): Promise<upsertTeamPlayer.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...upsertTeamPlayer.METADATA,
      template: upsertTeamPlayer.METADATA.path,
      path: upsertTeamPlayer.path(teamId),
    },
    dto,
  );
}
export namespace upsertTeamPlayer {
  export type Body = Primitive<CreateTeamPlayerDto>;
  export type Output = Primitive<TeamPlayer>;

  export const METADATA = {
    method: "PUT",
    path: "/teams/:teamId/players",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (teamId: string) =>
    `/teams/${encodeURIComponent(teamId?.toString() ?? "null")}/players`;
}
