import { User as UserEntity } from './entities/user.entity';
import { Inject, Injectable } from '@nestjs/common';
import { Kysely, Selectable } from 'kysely';
import { DB } from '../infrastructure/database/types';
import { CreateUserDto } from './dto/create-user.dto';

export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');

// Repository contract
export interface IUsersRepository {
  create(user: CreateUserDto): Promise<UserEntity>;
  findAll(): Promise<UserEntity[]>;
  findOne(id: number): Promise<UserEntity | null>;
  update(id: number, user: Partial<UserEntity>): Promise<UserEntity | null>;
  remove(id: number): Promise<boolean>;
}

// In-memory implementation (great for testing or prototyping)

/* eslint-disable @typescript-eslint/require-await */
export class InMemoryUsersRepository implements IUsersRepository {
  private users: UserEntity[] = [];

  async create(user: CreateUserDto): Promise<UserEntity> {
    const userWithId: UserEntity = { userId: this.users.length + 1, ...user };
    this.users.push(userWithId);
    return userWithId;
  }

  async findAll(): Promise<UserEntity[]> {
    return this.users;
  }

  async findOne(id: number): Promise<UserEntity | null> {
    return this.users.find((u) => u.userId === id) ?? null;
  }

  async update(id: number, user: Partial<UserEntity>): Promise<UserEntity | null> {
    const index = this.users.findIndex((u) => u.userId === id);
    if (index === -1) return null;

    this.users[index] = { ...this.users[index], ...user };
    return this.users[index];
  }

  async remove(id: number): Promise<boolean> {
    const index = this.users.findIndex((u) => u.userId === id);
    if (index === -1) return false;

    this.users.splice(index, 1);
    return true;
  }

  // Helper for tests
  seed(users: UserEntity[]) {
    this.users = users;
  }
}
/* eslint-enable @typescript-eslint/require-await */

@Injectable()
export class DatabaseUsersRepository implements IUsersRepository {
  constructor(@Inject('DB_CONNECTION') private readonly db: Kysely<DB>) {}

  private mapToEntity = (row: Selectable<DB['user']>): UserEntity =>
    new UserEntity(
      row.userId!, // generated by DB
      row.name,
      row.email,
    );

  async create(user: CreateUserDto): Promise<UserEntity> {
    const result = await this.db
      .insertInto('user')
      .values({
        name: user.name,
        email: user.email,
      })
      .returningAll()
      .executeTakeFirstOrThrow();

    return this.mapToEntity(result);
  }

  async findAll(): Promise<UserEntity[]> {
    const rows: Selectable<DB['user']>[] = await this.db.selectFrom('user').selectAll().execute();
    return rows.map(this.mapToEntity);
  }

  async findOne(id: number): Promise<UserEntity | null> {
    const row = await this.db
      .selectFrom('user')
      .selectAll()
      .where('userId', '=', id)
      .executeTakeFirst();

    return row ? this.mapToEntity(row) : null;
  }

  async update(id: number, user: Partial<UserEntity>): Promise<UserEntity | null> {
    const result = await this.db
      .updateTable('user')
      .set({
        ...(user.name && { name: user.name }),
        ...(user.email && { email: user.email }),
      })
      .where('userId', '=', id)
      .returningAll()
      .executeTakeFirst();

    return result ? this.mapToEntity(result) : null;
  }

  async remove(id: number): Promise<boolean> {
    const result = await this.db.deleteFrom('user').where('userId', '=', id).executeTakeFirst();
    return (result?.numDeletedRows ?? 0n) > 0n;
  }
}
