/**
 * @packageDocumentation
 * @module api.functional.teams
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreateTeamDto,
  ITeam,
  Team,
  UpdateTeamDto,
} from "../../../../../teams/entities/team.entity";

export * as players from "./players/index";

/**
 * @controller TeamsController.create
 * @path POST /teams
 * @accessor api.functional.teams.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createTeamDto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    createTeamDto,
  );
}
export namespace create {
  export type Body = Primitive<CreateTeamDto>;
  export type Output = Primitive<Team>;

  export const METADATA = {
    method: "POST",
    path: "/teams",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/teams";
}

/**
 * @controller TeamsController.findAll
 * @path GET /teams
 * @accessor api.functional.teams.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(),
  });
}
export namespace findAll {
  export type Output = Primitive<ITeam[]>;

  export const METADATA = {
    method: "GET",
    path: "/teams",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/teams";
}

/**
 * @controller TeamsController.findOne
 * @path GET /teams/:id
 * @accessor api.functional.teams.findOne
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    template: findOne.METADATA.path,
    path: findOne.path(id),
  });
}
export namespace findOne {
  export type Output = Primitive<ITeam>;

  export const METADATA = {
    method: "GET",
    path: "/teams/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/teams/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller TeamsController.update
 * @path PATCH /teams/:id
 * @accessor api.functional.teams.update
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  updateTeamDto: update.Body,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...update.METADATA,
      template: update.METADATA.path,
      path: update.path(id),
    },
    updateTeamDto,
  );
}
export namespace update {
  export type Body = Primitive<UpdateTeamDto>;
  export type Output = Primitive<Team>;

  export const METADATA = {
    method: "PATCH",
    path: "/teams/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/teams/${encodeURIComponent(id?.toString() ?? "null")}`;
}

/**
 * @controller TeamsController.remove
 * @path DELETE /teams/:id
 * @accessor api.functional.teams.remove
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    template: remove.METADATA.path,
    path: remove.path(id),
  });
}
export namespace remove {
  export const METADATA = {
    method: "DELETE",
    path: "/teams/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/teams/${encodeURIComponent(id?.toString() ?? "null")}`;
}
