/**
 * @packageDocumentation
 * @module api.functional.sleeper.state
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type { ISleeperState } from "../../../../../../sleeper/entities/sleeper.entity";

/**
 * @controller SleeperController.getState
 * @path GET /sleeper/state
 * @accessor api.functional.sleeper.state.getState
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getState(
  connection: IConnection,
): Promise<getState.Output> {
  return PlainFetcher.fetch(connection, {
    ...getState.METADATA,
    template: getState.METADATA.path,
    path: getState.path(),
  });
}
export namespace getState {
  export type Output = Primitive<ISleeperState>;

  export const METADATA = {
    method: "GET",
    path: "/sleeper/state",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/sleeper/state";
}
