/**
 * @packageDocumentation
 * @module api.functional.users.leagues
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { UserLeagues } from '@/users/entities/user.entity';
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * @controller UsersController.getLeaguesForUser
 * @path GET /users/:id/leagues
 * @accessor api.functional.users.leagues.getLeaguesForUser
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLeaguesForUser(
  connection: IConnection,
  id: string,
): Promise<getLeaguesForUser.Output> {
  return PlainFetcher.fetch(connection, {
    ...getLeaguesForUser.METADATA,
    template: getLeaguesForUser.METADATA.path,
    path: getLeaguesForUser.path(id),
  });
}
export namespace getLeaguesForUser {
  export type Output = Primitive<UserLeagues[]>;

  export const METADATA = {
    method: "GET",
    path: "/users/:id/leagues",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/users/${encodeURIComponent(id?.toString() ?? "null")}/leagues`;
}
