/**
 * @packageDocumentation
 * @module api.functional.leagues.teams
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * Get all teams/entries for a league
 * @controller LeaguesController.getLeagueTeams
 * @path GET /leagues/:id/teams
 * @accessor api.functional.leagues.teams.getLeagueTeams
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getLeagueTeams(
  connection: IConnection,
  leagueId: string,
): Promise<getLeagueTeams.Output> {
  return PlainFetcher.fetch(connection, {
    ...getLeagueTeams.METADATA,
    template: getLeagueTeams.METADATA.path,
    path: getLeagueTeams.path(leagueId),
  });
}
export namespace getLeagueTeams {
  export type Output = Primitive<ITeam[]>;

  export const METADATA = {
    method: "GET",
    path: "/leagues/:id/teams",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (leagueId: string) =>
    `/leagues/${encodeURIComponent(leagueId?.toString() ?? "null")}/teams`;
}
