/**
 * @packageDocumentation
 * @module api.functional.teams.cases
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { TeamEntryCasesResponseDto } from "@/teams/entities/team-entry.entity";
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

/**
 * GET /teams/:teamId/cases?position=RB
 *
 * Returns the current "cases" for the team & position.
 *
 * Does NOT reveal which player is inside which case — only metadata
 * such as boxNumber & boxStatus ("hidden", "opened", etc.).
 * @controller TeamsController.getTeamCases
 * @path GET /teams/:teamId/cases
 * @accessor api.functional.teams.cases.getTeamCases
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getTeamCases(
  connection: IConnection,
  teamId: string,
  position: string,
): Promise<getTeamCases.Output> {
  return PlainFetcher.fetch(connection, {
    ...getTeamCases.METADATA,
    template: getTeamCases.METADATA.path,
    path: getTeamCases.path(teamId, position),
  });
}
export namespace getTeamCases {
  export type Output = Primitive<TeamEntryCasesResponseDto>;

  export const METADATA = {
    method: "GET",
    path: "/teams/:teamId/cases",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (teamId: string, position: string) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries({
      position: position,
    } as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = `/teams/${encodeURIComponent(teamId?.toString() ?? "null")}/cases`;
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
