/**
 * @packageDocumentation
 * @module api.functional.leagues.users
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  AddLeagueUserDto,
  ILeagueUser,
  UpdateLeagueUserDto,
} from "../../../../../../leagues/entities/league-user.entity";

/**
 * @controller LeaguesController.findLeagueUsers
 * @path GET /leagues/:id/users
 * @accessor api.functional.leagues.users.findLeagueUsers
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findLeagueUsers(
  connection: IConnection,
  id: string,
): Promise<findLeagueUsers.Output> {
  return PlainFetcher.fetch(connection, {
    ...findLeagueUsers.METADATA,
    template: findLeagueUsers.METADATA.path,
    path: findLeagueUsers.path(id),
  });
}
export namespace findLeagueUsers {
  export type Output = Primitive<LeagueUser[]>;

  export const METADATA = {
    method: "GET",
    path: "/leagues/:id/users",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (id: string) =>
    `/leagues/${encodeURIComponent(id?.toString() ?? "null")}/users`;
}

/**
 * @controller LeaguesController.addLeagueUser
 * @path PUT /leagues/:id/users
 * @accessor api.functional.leagues.users.addLeagueUser
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function addLeagueUser(
  connection: IConnection,
  leagueId: string,
  addLeagueUserDto: addLeagueUser.Body,
): Promise<addLeagueUser.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...addLeagueUser.METADATA,
      template: addLeagueUser.METADATA.path,
      path: addLeagueUser.path(leagueId),
    },
    addLeagueUserDto,
  );
}
export namespace addLeagueUser {
  export type Body = Primitive<AddLeagueUserDto>;
  export type Output = Primitive<ILeagueUser>;

  export const METADATA = {
    method: "PUT",
    path: "/leagues/:id/users",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (leagueId: string) =>
    `/leagues/${encodeURIComponent(leagueId?.toString() ?? "null")}/users`;
}

/**
 * @controller LeaguesController.removeLeagueUser
 * @path DELETE /leagues/:id/users/:userId
 * @accessor api.functional.leagues.users.removeLeagueUser
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function removeLeagueUser(
  connection: IConnection,
  leagueId: string,
  userId: string,
): Promise<removeLeagueUser.Output> {
  return PlainFetcher.fetch(connection, {
    ...removeLeagueUser.METADATA,
    template: removeLeagueUser.METADATA.path,
    path: removeLeagueUser.path(leagueId, userId),
  });
}
export namespace removeLeagueUser {
  export type Output = Primitive<boolean>;

  export const METADATA = {
    method: "DELETE",
    path: "/leagues/:id/users/:userId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (leagueId: string, userId: string) =>
    `/leagues/${encodeURIComponent(leagueId?.toString() ?? "null")}/users/${encodeURIComponent(userId?.toString() ?? "null")}`;
}

/**
 * @controller LeaguesController.updateLeagueUser
 * @path PUT /leagues/:id/users/:userId
 * @accessor api.functional.leagues.users.updateLeagueUser
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateLeagueUser(
  connection: IConnection,
  leagueId: string,
  userId: string,
  updateLeagueUserDto: updateLeagueUser.Body,
): Promise<updateLeagueUser.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateLeagueUser.METADATA,
      template: updateLeagueUser.METADATA.path,
      path: updateLeagueUser.path(leagueId, userId),
    },
    updateLeagueUserDto,
  );
}
export namespace updateLeagueUser {
  export type Body = Primitive<UpdateLeagueUserDto>;
  export type Output = Primitive<ILeagueUser>;

  export const METADATA = {
    method: "PUT",
    path: "/leagues/:id/users/:userId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (leagueId: string, userId: string) =>
    `/leagues/${encodeURIComponent(leagueId?.toString() ?? "null")}/users/${encodeURIComponent(userId?.toString() ?? "null")}`;
}
