/**
 * @packageDocumentation
 * @module api.functional.events
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import type { Primitive } from "typia";

import type {
  CreateEventGroupDto,
  EventGroup,
} from "../../../../../events/entities/event-group.entity";

/**
 * @controller EventGroupsController.create
 * @path POST /event-groups
 * @accessor api.functional.events.create
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createEventGroupDto: create.Body,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...create.METADATA,
      template: create.METADATA.path,
      path: create.path(),
    },
    createEventGroupDto,
  );
}
export namespace create {
  export type Body = Primitive<CreateEventGroupDto>;
  export type Output = Primitive<EventGroup>;

  export const METADATA = {
    method: "POST",
    path: "/event-groups",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/event-groups";
}

/**
 * @controller EventGroupsController.findAll
 * @path GET /event-groups
 * @accessor api.functional.events.findAll
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    template: findAll.METADATA.path,
    path: findAll.path(),
  });
}
export namespace findAll {
  export type Output = Primitive<EventGroup[]>;

  export const METADATA = {
    method: "GET",
    path: "/event-groups",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/event-groups";
}